{
    "Total": 601,
    "Page": 31,
    "Letters": [
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1272207,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "گزارش فعالیت ماهانه دوره ۱ ماهه منتهی به  ۱۴۰۳/۰۸/۳۰",
            "LetterCode": "ن-۳۱",
            "SentDateTime": "۱۴۰۳/۰۹/۰۲ ۱۲:۵۶:۳۱",
            "PublishDateTime": "۱۴۰۳/۰۹/۰۲ ۱۲:۵۶:۳۱",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=paeNz7zx313vuslDaQqkMg%3d%3d&rt=2&let=8&ct=0&ft=-1",
            "HasExcel": True,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": False,
            "AttachmentUrl": "",
            "PdfUrl": "DownloadFile.aspx?hs=paeNz7zx313vuslDaQqkMg%3d%3d&ft=1005&let=8",
            "ExcelUrl": "https://excel.codal.ir/service/Excel/GetAll/paeNz7zx313vuslDaQqkMg%3d%3d/0",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1265571,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "معرفی /تغییر در ترکیب اعضای هیئت مدیره/مدیر عامل",
            "LetterCode": "ن-۴۵",
            "SentDateTime": "۱۴۰۳/۰۸/۱۳ ۱۸:۴۴:۱۴",
            "PublishDateTime": "۱۴۰۳/۰۸/۱۳ ۱۸:۴۴:۱۴",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=SlMPOOObOOOJrhTOvdo0EP1fUqOOObOOOA%3d%3d&rt=2&let=19&ct=0&ft=-1",
            "HasExcel": False,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=SlMPOOObOOOJrhTOvdo0EP1fUqOOObOOOA%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=SlMPOOObOOOJrhTOvdo0EP1fUqOOObOOOA%3d%3d&ft=1005&let=19",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1259212,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "گزارش فعالیت ماهانه دوره ۱ ماهه منتهی به  ۱۴۰۳/۰۷/۳۰",
            "LetterCode": "ن-۳۱",
            "SentDateTime": "۱۴۰۳/۰۸/۰۱ ۱۲:۳۴:۲۰",
            "PublishDateTime": "۱۴۰۳/۰۸/۰۱ ۱۲:۳۴:۲۰",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=mC8QQQaQQQzI5FdRV82gJMHGxSCw%3d%3d&rt=2&let=8&ct=0&ft=-1",
            "HasExcel": True,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": False,
            "AttachmentUrl": "",
            "PdfUrl": "DownloadFile.aspx?hs=mC8QQQaQQQzI5FdRV82gJMHGxSCw%3d%3d&ft=1005&let=8",
            "ExcelUrl": "https://excel.codal.ir/service/Excel/GetAll/mC8QQQaQQQzI5FdRV82gJMHGxSCw%3d%3d/0",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1254263,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "گزارش فعالیت ماهانه دوره ۱ ماهه منتهی به  ۱۴۰۳/۰۶/۳۱(اصلاحیه)",
            "LetterCode": "ن-۳۱",
            "SentDateTime": "۱۴۰۳/۰۷/۲۲ ۱۹:۰۶:۵۶",
            "PublishDateTime": "۱۴۰۳/۰۷/۲۲ ۱۹:۰۶:۵۶",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=OOObOOO81uxt3pQQQaQQQywDYQQQaQQQBdgm1IJA%3d%3d&rt=2&let=8&ct=0&ft=-1",
            "HasExcel": True,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": False,
            "AttachmentUrl": "",
            "PdfUrl": "DownloadFile.aspx?hs=OOObOOO81uxt3pQQQaQQQywDYQQQaQQQBdgm1IJA%3d%3d&ft=1005&let=8",
            "ExcelUrl": "https://excel.codal.ir/service/Excel/GetAll/OOObOOO81uxt3pQQQaQQQywDYQQQaQQQBdgm1IJA%3d%3d/0",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1254098,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "اطلاعات و صورت\u200cهای مالی میاندوره\u200cای  دوره ۹ ماهه منتهی به  ۱۴۰۳/۰۶/۳۱ (حسابرسی نشده)",
            "LetterCode": "ن-۱۰",
            "SentDateTime": "۱۴۰۳/۰۷/۲۱ ۰۹:۴۱:۴۹",
            "PublishDateTime": "۱۴۰۳/۰۷/۲۱ ۰۹:۴۱:۴۹",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=EXFC8bWg4jRFyhgnkZpqrA%3d%3d&rt=2&let=6&ct=0&ft=-1",
            "HasExcel": True,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=EXFC8bWg4jRFyhgnkZpqrA%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=EXFC8bWg4jRFyhgnkZpqrA%3d%3d&ft=1005&let=6",
            "ExcelUrl": "https://excel.codal.ir/service/Excel/GetAll/EXFC8bWg4jRFyhgnkZpqrA%3d%3d/0",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1252407,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "افشای اطلاعات بااهمیت - (افشای معاملات موضوع ماده ۱۲۹ لایحه اصلاحی قانون تجارت یا سایر اشخاص وابسته - گروه ب) منتهی به سال مالی ۱۴۰۳/۰۹/۳۰",
            "LetterCode": "ن-۲۰",
            "SentDateTime": "۱۴۰۳/۰۷/۱۰ ۱۰:۱۹:۱۳",
            "PublishDateTime": "۱۴۰۳/۰۷/۱۰ ۱۰:۱۹:۱۳",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=yGEsDJOEKlxM2DOOObOOO2fytNWA%3d%3d&rt=2&let=11&ct=0&ft=-1",
            "HasExcel": False,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=yGEsDJOEKlxM2DOOObOOO2fytNWA%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=yGEsDJOEKlxM2DOOObOOO2fytNWA%3d%3d&ft=1005&let=11",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1252274,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "افشای اطلاعات بااهمیت - (نقل و انتقال دارایی های ثابت شرکت - گروه الف) منتهی به سال مالی ۱۴۰۳/۰۹/۳۰",
            "LetterCode": "ن-۲۰",
            "SentDateTime": "۱۴۰۳/۰۷/۱۰ ۱۰:۰۵:۳۷",
            "PublishDateTime": "۱۴۰۳/۰۷/۱۰ ۱۰:۰۵:۳۷",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=aX23NgGrrXIuj4t64ftXFg%3d%3d&rt=2&let=11&ct=0&ft=-1",
            "HasExcel": False,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=aX23NgGrrXIuj4t64ftXFg%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=aX23NgGrrXIuj4t64ftXFg%3d%3d&ft=1005&let=11",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1248299,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "آگهی ثبت افزایش سرمایه(اصلاحیه)",
            "LetterCode": "ن-۶۷",
            "SentDateTime": "۱۴۰۳/۰۶/۲۹ ۱۷:۰۸:۲۰",
            "PublishDateTime": "۱۴۰۳/۰۶/۲۹ ۱۷:۰۸:۲۰",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=Jhj6fBYvXrUapFKOjzkAxw%3d%3d&rt=2&let=28&ct=0&ft=-1",
            "HasExcel": False,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=Jhj6fBYvXrUapFKOjzkAxw%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=Jhj6fBYvXrUapFKOjzkAxw%3d%3d&ft=1005&let=28",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1247556,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "گزارش فعالیت ماهانه دوره ۱ ماهه منتهی به  ۱۴۰۳/۰۶/۳۱",
            "LetterCode": "ن-۳۱",
            "SentDateTime": "۱۴۰۳/۰۶/۲۸ ۲۱:۵۳:۱۹",
            "PublishDateTime": "۱۴۰۳/۰۶/۲۸ ۲۱:۵۳:۱۹",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=aI02Q3TtpOOObOOOVIAJzfYMOOObOOOX6w%3d%3d&rt=2&let=8&ct=0&ft=-1",
            "HasExcel": True,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": False,
            "AttachmentUrl": "",
            "PdfUrl": "DownloadFile.aspx?hs=aI02Q3TtpOOObOOOVIAJzfYMOOObOOOX6w%3d%3d&ft=1005&let=8",
            "ExcelUrl": "https://excel.codal.ir/service/Excel/GetAll/aI02Q3TtpOOObOOOVIAJzfYMOOObOOOX6w%3d%3d/0",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1247037,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "آگهی ثبت افزایش سرمایه",
            "LetterCode": "ن-۶۷",
            "SentDateTime": "۱۴۰۳/۰۶/۲۶ ۱۹:۴۱:۳۱",
            "PublishDateTime": "۱۴۰۳/۰۶/۲۶ ۱۹:۴۱:۳۱",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=eADM5m1Wt5wHIOIPs0Ho5Q%3d%3d&rt=2&let=28&ct=0&ft=-1",
            "HasExcel": False,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=eADM5m1Wt5wHIOIPs0Ho5Q%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=eADM5m1Wt5wHIOIPs0Ho5Q%3d%3d&ft=1005&let=28",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1243994,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "معرفی /تغییر در ترکیب اعضای هیئت مدیره/مدیر عامل",
            "LetterCode": "ن-۴۵",
            "SentDateTime": "۱۴۰۳/۰۶/۱۸ ۱۴:۴۵:۱۳",
            "PublishDateTime": "۱۴۰۳/۰۶/۱۸ ۱۴:۴۵:۱۳",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=eySOvIKBffsHsGi1m8vqsA%3d%3d&rt=2&let=19&ct=0&ft=-1",
            "HasExcel": False,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=eySOvIKBffsHsGi1m8vqsA%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=eySOvIKBffsHsGi1m8vqsA%3d%3d&ft=1005&let=19",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1242429,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "نتایج حاصل از فروش حق تقدم های استفاده نشده",
            "LetterCode": "ن-۶۶",
            "SentDateTime": "۱۴۰۳/۰۶/۱۱ ۱۰:۵۴:۴۸",
            "PublishDateTime": "۱۴۰۳/۰۶/۱۱ ۱۰:۵۴:۴۸",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=AXnXCN8c7tPA1lnm5PeP9g%3d%3d&rt=2&let=119&ct=0&ft=-1",
            "HasExcel": False,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=AXnXCN8c7tPA1lnm5PeP9g%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=AXnXCN8c7tPA1lnm5PeP9g%3d%3d&ft=1005&let=119",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1239131,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "گزارش فعالیت ماهانه دوره ۱ ماهه منتهی به  ۱۴۰۳/۰۵/۳۱",
            "LetterCode": "ن-۳۱",
            "SentDateTime": "۱۴۰۳/۰۶/۰۳ ۲۰:۵۰:۰۴",
            "PublishDateTime": "۱۴۰۳/۰۶/۰۳ ۲۰:۵۰:۰۴",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=daFoNBa8o74QQQaQQQbe8ozljOEg%3d%3d&rt=2&let=8&ct=0&ft=-1",
            "HasExcel": True,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": False,
            "AttachmentUrl": "",
            "PdfUrl": "DownloadFile.aspx?hs=daFoNBa8o74QQQaQQQbe8ozljOEg%3d%3d&ft=1005&let=8",
            "ExcelUrl": "https://excel.codal.ir/service/Excel/GetAll/daFoNBa8o74QQQaQQQbe8ozljOEg%3d%3d/0",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1235210,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "اطلاعات و صورت\u200cهای مالی میاندوره\u200cای  دوره ۶ ماهه منتهی به  ۱۴۰۳/۰۳/۳۱ (حسابرسی شده)",
            "LetterCode": "ن-۱۰",
            "SentDateTime": "۱۴۰۳/۰۵/۲۷ ۲۱:۰۲:۴۲",
            "PublishDateTime": "۱۴۰۳/۰۵/۲۷ ۲۱:۰۲:۴۲",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=ozjxQkYOG7vRLmD%2bXgG6bQ%3d%3d&rt=2&let=6&ct=0&ft=-1",
            "HasExcel": True,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=ozjxQkYOG7vRLmDOOObOOOXgG6bQ%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=ozjxQkYOG7vRLmDOOObOOOXgG6bQ%3d%3d&ft=1005&let=6",
            "ExcelUrl": "https://excel.codal.ir/service/Excel/GetAll/ozjxQkYOG7vRLmDOOObOOOXgG6bQ%3d%3d/0",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1234511,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "تمدید اعلامیه پذیره نویسی عمومی",
            "LetterCode": "ن-۶۵",
            "SentDateTime": "۱۴۰۳/۰۵/۲۴ ۰۹:۰۹:۰۰",
            "PublishDateTime": "۱۴۰۳/۰۵/۲۴ ۰۹:۰۹:۰۰",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=X79W1JZWOzJrba2BKTTwag%3d%3d&rt=2&let=27&ct=0&ft=-1",
            "HasExcel": False,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=X79W1JZWOzJrba2BKTTwag%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=X79W1JZWOzJrba2BKTTwag%3d%3d&ft=1005&let=27",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1229081,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "اعلامیه پذیره نویسی عمومی",
            "LetterCode": "ن-۶۵",
            "SentDateTime": "۱۴۰۳/۰۵/۱۳ ۰۸:۰۵:۵۰",
            "PublishDateTime": "۱۴۰۳/۰۵/۱۳ ۰۸:۰۵:۵۰",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=KLMZRclAf%2bul8IEeOMNUAw%3d%3d&rt=2&let=27&ct=0&ft=-1",
            "HasExcel": False,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=KLMZRclAfOOObOOOul8IEeOMNUAw%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=KLMZRclAfOOObOOOul8IEeOMNUAw%3d%3d&ft=1005&let=27",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1221708,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "گزارش فعالیت ماهانه دوره ۱ ماهه منتهی به  ۱۴۰۳/۰۴/۳۱",
            "LetterCode": "ن-۳۱",
            "SentDateTime": "۱۴۰۳/۰۵/۰۱ ۱۳:۰۸:۱۷",
            "PublishDateTime": "۱۴۰۳/۰۵/۰۱ ۱۳:۰۸:۱۷",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=6BvbGXlzoDyOGADUuG3uUw%3d%3d&rt=2&let=8&ct=0&ft=-1",
            "HasExcel": True,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": False,
            "AttachmentUrl": "",
            "PdfUrl": "DownloadFile.aspx?hs=6BvbGXlzoDyOGADUuG3uUw%3d%3d&ft=1005&let=8",
            "ExcelUrl": "https://excel.codal.ir/service/Excel/GetAll/6BvbGXlzoDyOGADUuG3uUw%3d%3d/0",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1220007,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "اطلاعات و صورت\u200cهای مالی میاندوره\u200cای  دوره ۶ ماهه منتهی به  ۱۴۰۳/۰۳/۳۱ (حسابرسی نشده)",
            "LetterCode": "ن-۱۰",
            "SentDateTime": "۱۴۰۳/۰۴/۳۰ ۱۷:۵۷:۱۵",
            "PublishDateTime": "۱۴۰۳/۰۴/۳۰ ۱۷:۵۷:۱۵",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=LreSWL5JglAVjh1pJkQu8Q%3d%3d&rt=2&let=6&ct=0&ft=-1",
            "HasExcel": True,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=LreSWL5JglAVjh1pJkQu8Q%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=LreSWL5JglAVjh1pJkQu8Q%3d%3d&ft=1005&let=6",
            "ExcelUrl": "https://excel.codal.ir/service/Excel/GetAll/LreSWL5JglAVjh1pJkQu8Q%3d%3d/0",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1216745,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "اساسنامه شرکت مصوب مجمع عمومی فوق العاده مورخ ۱۴۰۳/۰۲/۳۰",
            "LetterCode": "ن-۴۳",
            "SentDateTime": "۱۴۰۳/۰۴/۲۰ ۱۰:۵۷:۰۶",
            "PublishDateTime": "۱۴۰۳/۰۴/۲۰ ۱۰:۵۷:۰۶",
            "HasHtml": True,
            "IsEstimate": False,
            "Url": "/Reports/Decision.aspx?LetterSerial=60BR5Qz5Uv8%2b7JH%2b0feWQA%3d%3d&rt=2&let=120&ct=0&ft=-1",
            "HasExcel": False,
            "HasPdf": True,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=60BR5Qz5Uv8OOObOOO7JHOOObOOO0feWQA%3d%3d",
            "PdfUrl": "DownloadFile.aspx?hs=60BR5Qz5Uv8OOObOOO7JHOOObOOO0feWQA%3d%3d&ft=1005&let=120",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
        {
            "SuperVision": {"UnderSupervision": 0, "AdditionalInfo": "", "Reasons": []},
            "TracingNo": 1211792,
            "Symbol": "پردیس",
            "CompanyName": "سرمایه گذاری پردیس",
            "UnderSupervision": 0,
            "Title": "آگهی ثبت تصمیمات مجمع عمومی فوق العاده (بجز تغییرات سرمایه) دوره ۱۲ ماهه منتهی به  ۱۴۰۳/۰۹/۳۰",
            "LetterCode": "ن-۴۲",
            "SentDateTime": "۱۴۰۳/۰۴/۱۱ ۱۵:۲۳:۱۹",
            "PublishDateTime": "۱۴۰۳/۰۴/۱۱ ۱۵:۲۳:۱۹",
            "HasHtml": False,
            "IsEstimate": False,
            "Url": "/Reports/Attachment.aspx?LetterSerial=adUZMszkLf1ccRJ6z6zHfg%3d%3d",
            "HasExcel": False,
            "HasPdf": False,
            "HasXbrl": False,
            "HasAttachment": True,
            "AttachmentUrl": "/Reports/Attachment.aspx?LetterSerial=adUZMszkLf1ccRJ6z6zHfg%3d%3d",
            "PdfUrl": "",
            "ExcelUrl": "",
            "XbrlUrl": "",
            "TedanUrl": "http://www.tedan.ir",
        },
    ],
    "IsAttacker": False,
}
