version: "3"
services:
  mongo:
    image: mongo:4.4.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - /data/mongo:/data/db
    ports:
      - "27017:27017"
    restart: always