version: "3"
services:
  mongo:
    image: mongo:4.4.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - /data/codal:/data/db
    ports:
      - "${MONGO_PORT:-27017}:27017"
    restart: always

  dagster-daemon:
    build: .
    working_dir: /apps
    command: dagster-daemon run
    env_file: .env
    volumes:
      - /dagster:/opt/dagster
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./dagster.yaml:/opt/dagster/dagster.yaml
      - .:/apps
    restart: always

  dagster-webserver:
    build: .
    working_dir: /apps
    command: dagster-webserver -h 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dagster:/opt/dagster
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ./dagster.yaml:/opt/dagster/dagster.yaml
      - .:/apps
    restart: always
    depends_on:
      - dagster-daemon
